version: '3'

services:
  keycloak:
    image: "registry.okina.fr/na/keycloak"
    volumes:
      - ../naq_theme:/opt/jboss/keycloak/themes/naq
    ports:
      - "12000:8080"
    environment:
      POSTGRES_DATABASE:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      DB_VENDOR: postgres
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
