version: '3'

services:
  keycloak:
    image: "registry.okina.fr/na/naq-keycloak-server:v1.0"
    volumes:
      - ../naq_theme:/opt/jboss/keycloak/themes/naq
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      POSTGRES_DATABASE:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      DB_VENDOR: POSTGRES
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    container_name: naq-keycloak-server
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: naq-keycloak-db
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
